### ISSUE TITLE
Theme chooser/installer

### ISSUE THREAD

**Issue by opatry** [AdamWhitcroft/Apaxy#10]
Hi,

are you interested in a theme chooser/installer.
Currently, the process of installation a little bit manual, I suggest a shell script with user prompt (with some well default values according to the current working directory) to define the htaccess file (and move the .txt to .htaccess (see #9)).

If there are several subfolders in a so called "themes" directory, ask for user to choose the one to be installed.

**Comment by AdamWhitcroft** [comment]
@opatry unfortunately that is far beyond my technical knowledge. I'm going to close this for now, but if you know how to or want to make an installer, please do!
