### ISSUE TITLE
add actual demo

### ISSUE THREAD

**Issue by snorpey** [AdamWhitcroft/Apaxy#27]
It would be nice if we could link to an actual demo of Apaxy instead of showing a screen shot. I think this would make it easier evaluate Apaxy and see how it looks and works on small screen devices.

If an actual demo is not feasible, maybe a we could link to an HTML + CSS dummy?

**Comment by AdamWhitcroft** [comment]
I used to have a demo, but I then moved over to GitHub to host my website.

I can work on an HTML + CSS dummy if you'd like, but links to people already using would be much easier cc @PeterDaveHello

**Comment by UksusoFF** [comment]
Demo: http://iamdrunk.ru/teach/ 
But available only russian day time

**Comment by PeterDaveHello** [comment]
hmmmm ... I just moved to nginx due to performance issue, should try to have a nginx version I think.

**Comment by PeterDaveHello** [comment]
@AdamWhitcroft I now use Apaxy back, see this real example:
http://ftp.yzu.edu.tw/ :smile:
