### ISSUE TITLE
Missed Type Description

### ISSUE THREAD

**Issue by UksusoFF** [AdamWhitcroft/Apaxy#31]
AddIconByType (TXT,/theme/icons/text.png) text/*
	AddIconByType (IMG,/theme/icons/image.png) image/*
	AddIconByType (SND,/theme/icons/audio.png) audio/*
	AddIconByType (VID,/theme/icons/video.png) video/*

**Comment by AdamWhitcroft** [comment]
Merged, so closing.

Thanks!
