### ISSUE TITLE
Question/Request for Download Count

### ISSUE THREAD

**Issue by grondinseane** [AdamWhitcroft/Apaxy#40]
I don't know if this is even possible, as this is all new to me. Can the displayed page have a download counter displayed per file? I know I can look up stats through other means, but I would like something displayed for the people visiting and downloading the files.

Thank you for such an amazing little gem. Apaxy is a great tool.

I apologize is this is not where this question belongs.

**Comment by AdamWhitcroft** [comment]
You're most welcome!

To be honest, I'm not sure. I can look into it for you, but I have a feeling this might not be possible.

**Comment by grondinseane** [comment]
Okay thank you. No worries if it's not possible :-)

**Comment by Giggitybyte** [comment]
I came here to ask this exact question. A download counter would be really nice!

**Comment by AdamWhitcroft** [comment]
`mod_autoindex` doesn't support any sort of download count as far as I can see. I'm going to close this for now. If someone finds out how to do it, we'll get it in.
