### ISSUE TITLE
Apaxy theme for static RunAbove file listings

### ISSUE THREAD

**Issue by szepeviktor** [AdamWhitcroft/Apaxy#41]
RunAbove (by OVH) provides Openstack object storage and static web hosting, file listings.

repo: https://github.com/szepeviktor/Apaxy4RunAbove
demo: http://mirror.szepe.net/

**Comment by AdamWhitcroft** [comment]
@szepeviktor what's the issue here?

**Comment by szepeviktor** [comment]
This is just a notification of Apaxy usage.
