### ISSUE TITLE
Uncaught TypeError: Cannot set property 'className' of undefined

### ISSUE THREAD

**Issue by lifeisfoo** [AdamWhitcroft/Apaxy#43]
Using the last version from git with a directory of only files.

**Comment by AdamWhitcroft** [comment]
@lifeisfoo can you grab the latest version and try again? If you're still encountering this problem let me know.

**Comment by AdamWhitcroft** [comment]
@lifeisfoo any update for me? I'd like to close this off if possible.

**Comment by lifeisfoo** [comment]
Now it seems to be ok.
