### ISSUE TITLE
Apk and ipa icons

### ISSUE THREAD

**Issue by lifeisfoo** [AdamWhitcroft/Apaxy#44]
Could you add the android and ios app package icons?

Thank you

**Comment by AdamWhitcroft** [comment]
@lifeisfoo what icon would you like to use for them? The icon collection I'm using can be found [here](http://tiheum.deviantart.com/art/Faenza-Icons-173323228). Let me know, and I'll slot them in for you.

**Comment by lifeisfoo** [comment]
Probably the zip archive icon, because .ipa and .apk are both .zip. 

See:
- https://en.wikipedia.org/wiki/.ipa
- https://en.wikipedia.org/wiki/Android_application_package

**Comment by AdamWhitcroft** [comment]
@lifeisfoo what about `package.png` as seen here - https://github.com/AdamWhitcroft/Apaxy/blob/master/apaxy/theme/icons/package.png

**Comment by lifeisfoo** [comment]
I'm ok with it 👍

**Comment by AdamWhitcroft** [comment]
Cool, added and sitting in develop branch. Thanks for the suggestion!
