### ISSUE TITLE
Keep description cell

### ISSUE THREAD

**Issue by AGoberg** [AdamWhitcroft/Apaxy#50]
I'd like to keep the Description cell in the table. How can I style it? Specifically the width of it?

**Comment by AdamWhitcroft** [comment]
@AGoberg Hey. First off, remove `+SuppressDescription` from the `htaccess` file. Then, in `theme/style.css` use sibling selectors to give it a style. You will probably need to tweak the widths of the existing columns (around line 84) to match.
