### ISSUE TITLE
ASK

### ISSUE THREAD

**Issue by blegoh** [AdamWhitcroft/Apaxy#56]
Can i use this for lighttpd ?

**Comment by woodrowbarlow** [comment]
i don't think lighttpd support htacess files, but you can probably use the css without much modification. you can apply the css using the `dir-listing.external-css` option in your lighttpd config. see here: http://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_ModDirlisting#dir-listingexternal-css

**Comment by AdamWhitcroft** [comment]
@blegoh are you ok if I close off this issue?

**Comment by blegoh** [comment]
@AdamWhitcroft no problem dude. i don't use lightttpd anymore :)
