### ISSUE TITLE
Folders created at the root directory of the example folder do not show the theme

### ISSUE THREAD

**Issue by adityai** [AdamWhitcroft/Apaxy#65]
I created folders in the root directory where the example files are placed. When I open the folder from the browser, it does not show the theme. It shows missing images on the page. When I copied the theme folder into this new folder, the theme displayed properly.

Is there a straightforward way of solving for this without having to copy the theme folder inside every folder and without symlinks inside each folder?

**Comment by woodrowbarlow** [comment]
See issue #62.
