### ISSUE TITLE
Cannot get Apaxy to work

### ISSUE THREAD

**Issue by vertigo3d** [AdamWhitcroft/Apaxy#66]
Hello,

I have a very basic setup.  I have Apache installed on Ubuntu and my path is /var/www/html/test.  There are a few files in the 'test' folder.  I followed the directions to copy the contents from apaxy to the 'test' folder and renamed htaccess.txt to .htaccess in both the test/ folder and theme/folder.  However, when I browse to the directory, it shows the default file listing.  Is there something else that I need to do?  

Instructions seems pretty straightforward.  I restarted Apache but that didn't help.  Any assistance would be deeply appreciated.

**Comment by vertigo3d** [comment]
I was able to get this to work after adding the following lines to /etc/apache2/sites-available/000-default.conf:

**<Directory /var/www/html>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride All
                Order allow,deny
                allow from all
</Directory>**

Hopefully, it may help someone.  Maybe, someone else can describe why this worked :smile:...

**Comment by woodrowbarlow** [comment]
The `AllowOverride Indexes` option means "allow `.htaccess` files to override global apache configuration". Most Apache installs require this before you can use `.htaccess` files.

**Comment by AdamWhitcroft** [comment]
@vertigo3d Have you managed to get it working? If so, please let me know so I can close out this issue.

**Comment by vertigo3d** [comment]
Yes, it’s working.

**Comment by AdamWhitcroft** [comment]
Good stuff!
