### ISSUE TITLE
Installed Apaxy, not working

### ISSUE THREAD

**Issue by JacobGunther12** [AdamWhitcroft/Apaxy#69]
I use WampServer and I created a folder named "shared" in the same directory that contains the folder that holds my files. Here's a photo: 

![](http://i.imgur.com/Zu8KwmX.png)

It still doesn't work and I get this:

![](http://i.imgur.com/XCikBAQ.png)

Can this be fixed? Thanks!

**Comment by NeoMahler** [comment]
Same problem here. Help please!

**Comment by nodiscc** [comment]
`AllowOverride All` must be enabled in the apache configuration section for the directory where Apaxy is installed.

[`AllowOverride None`](https://httpd.apache.org/docs/2.4/mod/core.html#allowoverride) is the default value, which prevents Apaxy for from overriding the apache mod_index configuration through `.htaccess` files.

@NeoMahler @JacobGunther12 do you have this setting set to `All` in your apache or virtualhost config?

**Comment by NeoMahler** [comment]
@nodiscc No, I didn't have this setting. Now it works. Thanks!

**Comment by AdamWhitcroft** [comment]
@JacobGunther12 Can you confirm this is working now for you? I'd like to close this.

**Comment by AdamWhitcroft** [comment]
@NeoMahler Just a gentle nudge, are you happy with how it's working? I'd like to close this.

**Comment by NeoMahler** [comment]
Yes, it works perfect, you can close this issue.
