### ISSUE TITLE
Re-directing failure

### ISSUE THREAD

**Issue by scrolls-mckenzie** [AdamWhitcroft/apaxy#75]
Hello,

 Great theme but it seems to have broken redirects. When I click on a folder it does not redirect to the internal files. (ie. click on folder expecting to load the internal index.html but i get a white screen)

**Comment by scrolls-mckenzie** [comment]
My bad...

found the javascript in the footer and commented out. 

Cheers

**Comment by AdamWhitcroft** [comment]
@scrolls-mckenzie No worries, glad you got it sorted it out! If you're happy with the solution, I'll go ahead and close this issue out.

**Comment by ivanPrunier** [comment]
Hi, what is the exact code to comment? The redirection is not working for me :/

Thanks in advance! :)

**Comment by ivanPrunier** [comment]
My bad as well, just foud how to do it, thanks anyways, great creation!
