### ISSUE TITLE
Can't get this to work. Images not loading, or something. Sure it's an easy fix...

### ISSUE THREAD

**Issue by mR12KL** [AdamWhitcroft/apaxy#81]
I'm a complete noob. I've uploaded the files and renamed the htaccess's

I keep getting this:

https://i.gyazo.com/a2b705c058f6bd4527eea27fe98d72c2.png

Any help?

**Comment by mR12KL** [comment]
I did this:
`<Directory /var/www/>
	Options Indexes FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>`

but do i need to do this
`<Directory /var/www/[MY DIRECTORY]>
	Options Indexes FollowSymLinks
	AllowOverride All
	Require all granted
</Directory>`

as well?

**Comment by mR12KL** [comment]
https://i.gyazo.com/26b00f932bab1c8514d0c05c61353907.png

Now im getting this....

**Comment by monyxie** [comment]
I had the same issue but only in subdirectories. It worked fine in the root directory.
I was able to fix it by prepending a `/` to every path in the main .htaccess file.

**Comment by mR12KL** [comment]
Thanks!

**Comment by AdamWhitcroft** [comment]
@mR12KL Apologies for not getting back to you sooner, I've been travelling. Thanks for your help @monyxie, very much appreciated!
